In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics

### Loading the Dataset

In [3]:
heart = pd.read_csv("dvc_data/train.csv")
heart1 = pd.read_csv("dvc_data/test.csv")
su = pd.read_csv("dvc_data/submit_samples.csv")
heart.head()

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  ...  R3  R4  R5  R6  R7  O1  O2  \
0   1   0   1   0   1   0   1   0   0   0  ...   0   0   0   1   0   0   0   
1   2   0   1   0   1   0   1   1   0   0  ...   0   0   0   1   0   0   0   
2   3   1   1   0   1   1   1   0   0   0  ...   1   0   0   0   0   0   0   
3   4   1   1   0   1   0   0   0   0   0  ...   0   0   0   0   1   0   1   
4   5   0   0   1   1   0   0   0   0   0  ...   0   0   0   1   0   0   1   

   O3  O4  Y  
0   1   0  1  
1   1   0  1  
2   0   1  1  
3   0   0  1  
4   0   0  1  

[5 rows x 48 columns]

### Training and Validation Partition

In [4]:

heart1 = heart1.drop(['ID'], axis=1)
#heart1.fillna(0, inplace = True)
#heart1 = heart1.astype(float)

X = heart.drop(['Y','ID'], axis=1)
y =heart['Y'] 
#X.fillna(0, inplace = True)
#X = X.astype(float)
X.head()

G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  ...  R2  R3  R4  R5  R6  R7  O1  \
0   0   1   0   1   0   1   0   0   0   0  ...   0   0   0   0   1   0   0   
1   0   1   0   1   0   1   1   0   0   0  ...   0   0   0   0   1   0   0   
2   1   1   0   1   1   1   0   0   0   0  ...   0   1   0   0   0   0   0   
3   1   1   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   1   0   
4   0   0   1   1   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   

   O2  O3  O4  
0   0   1   0  
1   0   1   0  
2   0   0   1  
3   1   0   0  
4   1   0   0  

[5 rows x 46 columns]

In [5]:
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2)
# 建立分類器
clf = tree.DecisionTreeClassifier()
h_clf = clf.fit(train_X, train_y)

# 預測
test_y_predicted = h_clf.predict(test_X)
print(accuracy_score(test_y, test_y_predicted))
#print(test_y_predicted)

# 標準答案
print(h_clf.predict_proba(test_X)[:300])

0.6171875
[[0.61445783 0.         0.38554217]
 [0.55905512 0.         0.44094488]
 [0.55905512 0.         0.44094488]
 [0.6        0.1        0.3       ]
 [0.63414634 0.         0.36585366]
 [0.57142857 0.03571429 0.39285714]
 [1.         0.         0.        ]
 [0.77777778 0.         0.22222222]
 [0.66666667 0.         0.33333333]
 [0.55555556 0.         0.44444444]
 [0.33333333 0.         0.66666667]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.54545455 0.         0.45454545]
 [0.8125     0.         0.1875    ]
 [1.         0.         0.        ]
 [0.         0.875      0.125     ]
 [0.6        0.         0.4       ]
 [0.57142857 0.03571429 0.39285714]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.6        0.         0.4       ]
 [0.53846154 0.07692308 0.38461538]
 [0.57142857 0.03571429 0.39285714]
 [0.6        0.         0.4       ]
 [0.7        0.         0.3       ]
 [0.75       0.         0.25      ]
 [0.66666667 0.   

In [8]:
from sklearn.linear_model import LogisticRegression
import numpy as np

x_train = X
y_train = y
 
x_test = heart1
 
clf = LogisticRegression()
clf.fit(x_train, y_train)
 
# 返回预测标签
print(clf.predict(x_test))

# 返回预测属于某标签的概率
print(clf.predict_proba(x_test))


[3 2 1 1 2 1 2 2 1 1 1 1 2 1 2 1 1 2 1 1 2 1 2 2 1 2 2 2 2 2 1 2 1 1 1 2 1
 1 2 2 1 3 2 2 1 1 1 1 2 1 1 2 1 1 2 1 1 2 1 1 2 1 1 1 3 2 2 1 1 1 1 2 2 2
 1 1 2 2 1 1 2 1 1 3 2 1 1 1 3 1 2 1 1 2 1 2 2 1 1 1 2 2 2 2 1 1 1 1 1 2 1
 1 1 2 3 1 1 1 1 2 1 1 1 1 1 3 1 1 1 2 1 2 2 2 2 1 3 1 1 2 1 1 1 1 1 1 2 1
 2 1 2 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 2 2 1 2 1 1 2 2 1 1 1 1 2 1 2 1 1 1 1
 2 1 1 1 2 2 2 1 1 1 2 1 2 1 1 1 2 2 1 2 1 2 1 1 1 1 2 1 1 1 1 2 1 2 2 1 1
 2 1 1 2 1 2 1 1 3 2 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 2 1 1 1 1 1 2 1 2
 2 1 1 1 1 1 3 1 2 1 1 1 1 1 1 1 2 1 3 1 2 2 2 1 1 1 2 1 1 1 1 1 2 2 1 1 1
 1 1 2 1]
[[4.94968531e-01 1.22249726e-04 5.04909219e-01]
 [2.00091766e-01 7.07693813e-01 9.22144208e-02]
 [6.66229593e-01 7.61529431e-04 3.33008877e-01]
 [6.39897886e-01 6.25421128e-04 3.59476693e-01]
 [1.34652032e-01 7.91342958e-01 7.40050104e-02]
 [5.75388644e-01 1.76948021e-04 4.24434408e-01]
 [2.28457643e-01 6.62834293e-01 1.08708064e-01]
 [2.00091766e-01 7.07693813e-01 9.22144208e-02]
 [7.18

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [92]:
from sklearn.ensemble import GradientBoostingClassifier
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.2)
clf = GradientBoostingClassifier(n_estimators=200, max_depth=3,max_features=0.5,max_leaf_nodes=45)
clf.fit(train_x, train_y)

# print(clf.feature_importances_)
pred = clf.predict(test_x)
pred1 = clf.predict_proba(heart1)
print(accuracy_score(test_y, pred))
#print(clf.predict(heart1))
print(pred1)

0.6388888888888888
[[5.33826284e-01 2.78427565e-05 4.66145873e-01]
 [6.57172602e-03 9.87897236e-01 5.53103750e-03]
 [6.38025601e-01 1.39824811e-05 3.61960416e-01]
 [7.29686226e-01 9.39364566e-06 2.70304380e-01]
 [6.33557227e-03 9.90250828e-01 3.41360005e-03]
 [5.39379474e-01 1.62029235e-05 4.60604323e-01]
 [2.79618179e-03 9.95307210e-01 1.89660829e-03]
 [6.57172602e-03 9.87897236e-01 5.53103750e-03]
 [8.45703045e-01 1.76719932e-04 1.54120235e-01]
 [6.69846391e-01 1.67059578e-03 3.28483013e-01]
 [4.40292122e-01 1.12660051e-05 5.59696612e-01]
 [7.06457927e-01 1.65884416e-05 2.93525484e-01]
 [7.24513473e-05 9.99881528e-01 4.60202106e-05]
 [6.56154329e-01 1.73838207e-05 3.43828287e-01]
 [4.23117821e-02 9.34518576e-01 2.31696423e-02]
 [6.86743219e-01 1.82505999e-05 3.13238530e-01]
 [8.13538847e-01 1.23603446e-04 1.86337549e-01]
 [4.23117821e-02 9.34518576e-01 2.31696423e-02]
 [5.43269098e-01 2.92664637e-02 4.27464439e-01]
 [5.61015371e-01 1.84600355e-05 4.38966169e-01]
 [6.91869298e-03 9.87

### Prediction

In [94]:
print(pred1.shape)

(300, 3)


In [95]:
data = pd.DataFrame({'ID':su.ID ,'C1':pred1[:300,0],'C2':pred1[:300,1],'C3':pred1[:300,2]})
data.to_csv("dvc_data/010522.csv",index=False,sep=',')
print(data)

      ID        C1        C2        C3
0      1  0.533826  0.000028  0.466146
1      2  0.006572  0.987897  0.005531
2      3  0.638026  0.000014  0.361960
3      4  0.729686  0.000009  0.270304
4      5  0.006336  0.990251  0.003414
..   ...       ...       ...       ...
295  296  0.669846  0.001671  0.328483
296  297  0.612828  0.067402  0.319770
297  298  0.795815  0.000190  0.203994
298  299  0.023649  0.966792  0.009559
299  300  0.639139  0.000014  0.360847

[300 rows x 4 columns]


In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pylab as plt
heart = pd.read_csv("train.csv")
heart1 = pd.read_csv("test.csv")
su = pd.read_csv("submit_samples.csv")
heart.head()
heart1 = heart1.drop(['ID'], axis=1)
X = heart.drop(['Y','ID'], axis=1)
y =heart['Y'] 
#不管任何参数，都用默认的，拟合下数据看看
rf0 = RandomForestClassifier(oob_score=True,max_depth=8,max_leaf_nodes=45,n_estimators=300,max_features=0.7, 
                             min_samples_leaf=1, min_samples_split=3, random_state=1000,n_jobs=1,bootstrap=True)
rf0.fit(X,y)
print(rf0.oob_score_)
y_predprob = rf0.predict_proba(heart1)
print(y_predprob)

0.6703716568252865
[[5.86325220e-01 0.00000000e+00 4.13674780e-01]
 [6.58805376e-03 9.83801629e-01 9.61031680e-03]
 [6.27463654e-01 0.00000000e+00 3.72536346e-01]
 [6.12687849e-01 0.00000000e+00 3.87312151e-01]
 [2.44520342e-02 9.42356736e-01 3.31912295e-02]
 [5.70474602e-01 0.00000000e+00 4.29525398e-01]
 [1.17845118e-03 9.97608187e-01 1.21336169e-03]
 [6.58805376e-03 9.83801629e-01 9.61031680e-03]
 [7.29505557e-01 0.00000000e+00 2.70494443e-01]
 [7.32501556e-01 0.00000000e+00 2.67498444e-01]
 [5.74336961e-01 0.00000000e+00 4.25663039e-01]
 [6.25980241e-01 0.00000000e+00 3.74019759e-01]
 [4.77550049e-03 9.87816779e-01 7.40772080e-03]
 [5.98802206e-01 0.00000000e+00 4.01197794e-01]
 [3.12860355e-02 9.24433648e-01 4.42803168e-02]
 [6.25407828e-01 0.00000000e+00 3.74592172e-01]
 [8.13181436e-01 0.00000000e+00 1.86818564e-01]
 [3.12860355e-02 9.24433648e-01 4.42803168e-02]
 [5.81934496e-01 4.35496810e-02 3.74515823e-01]
 [5.78765140e-01 0.00000000e+00 4.21234860e-01]
 [7.22474455e-03 9.83